export enum EOrderStatus {
	SEARCHING = 'SEARCHING',
	ON_MANAGER = 'ON_MANAGER',
	WAITING = 'WAITING',
	IN_PROGRESS = 'IN_PROGRESS',
	CANCELED = 'CANCELED',
	REQUIRES_PAYMENT = 'REQUIRES_PAYMENT',
	DONE = 'DONE',
}
export enum EPerformerOrderStatus {
	WAITING = 'WAITING',
	IN_PATH = 'IN_PATH',
	AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
	IN_PROGRESS = 'IN_PROGRESS',
	BANNED = 'BANNED',
	DONE = 'DONE',
}
